title: "Beopsoo Kim"
description: "Academic homepage of Beopsoo Kim"
url: "https://beopsookim.github.io"
baseurl: ""
repository: "BeopsooKim/beopsookim.github.io"
timezone: Asia/Seoul

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-email-protect

collections:
  publications:
    output: false
  news:
    output: false
  showcase:
    output: false
  posts:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor/
  - .bundle/
  - .jekyll-cache/
  - node_modules/
  - README.md
